version: '3.9'
services:
  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_SESSIONS=5
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-chrome

networks:
  selenium-chrome:
    name: selenium-chrome
