version: '3.9'
services:
  bin-api:
    container_name: bin-api
    image: musatai/bin-api:${VERSION}
    ports:
      - 8082:8082
    environment:
      - VERSION=${VERSION}
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY}
      - APP_PORT=8082
      - ENV=${ENV}
    networks:
      - bin-api
      - redis

networks:
  bin-api:
    name: bin-api
  redis:
    name: redis

