version: '3.9'
services:
  bin-api:
    container_name: bin-api
    image: musatai/bin-api:1.0.0
    ports:
      - 8081:8081
    environment:
      - VERSION=1.0.0
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY}
      - APP_PORT=8081
    networks:
      - bin-api
      - redis

networks:
  bin-api:
    name: bin-api
  redis:
    name: redis

