version: '3.9'

services:
  jenkins:
    container_name: jenkins
    image: musatai/jenkins:1.0.0
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/musatai/Jenkins/jenkins_home:/var/jenkins_home
    networks:
      - jenkins

networks:
  jenkins:
    name: jenkins
