version: '3.9'
services:
  pornhub-album-shuffler:
    image: musatai/pornhub-album-shuffler:${VERSION}
    container_name: pornhub-album-shuffler
    environment:
      - SELENIUM_SERVER=selenium-chrome
      - SELENIUM_PORT=4444
      - PH_USERNAME=${PH_USERNAME}
      - PASSWORD=${PASSWORD}
    networks:
      - selenium-chrome
      - pornhub-album-shuffler

networks:
  selenium-chrome:
    name: selenium-chrome
  pornhub-album-shuffler:
    name: pornhub-album-shuffler
